name: Main Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      env:
        description: "The target environment. Default: qa"
        type: choice
        required: true
        default: qa
        options:
          - dev
          - qa
      marker:
        description: "Pytest marker (-m). Default: smoke"
        type: choice
        required: true
        default: smoke
        options:
          - regression
          - smoke

#  schedule:
#    - cron: '0 21 * * *'       # runs every day at 21:00 UTC

permissions:                    # Global permissions configuration starts here
  contents: write               # 'write' access to repository contents
  pull-requests: write          # 'write' access to pull requests

jobs:

  # Job 1: Code style and security checks
  code_check:
    name: Code Style and Security Check
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment using Poetry
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13.3'  # Adjust the Python version to your needs

      # Step 3: Install Poetry
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -

      # Step 4: Install dependencies with Poetry
      - name: Install dependencies
        run: |
          poetry install

      # Step 5: Run ruff for linting
      - name: Run ruff for linting
        run: |
          poetry run ruff check .

  # Job 2: Run tests
  run_tests:
    name: Run Tests
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' || github.event_name == 'schedule'
    needs: code_check  # Ensure code style and security checks pass first

    env:
      TEST_ENV: ${{ github.event.inputs.env || 'qa' }}
      TEST_MARKER: ${{ github.event.inputs.marker || 'smoke' }}

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment using Poetry
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13.3'

      # Step 3: Install Poetry
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 - --version 2.2.1

      # Step 4: Install dependencies with Poetry
      - name: Install dependencies
        run: |
          poetry install

      # Step 5: Run tests
      - name: Run tests
        run: |
          poetry run pytest --env "${TEST_ENV}" -m "${TEST_MARKER}"